### ISSUE TITLE
No datagrams for 7125 + Hydrins

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/MBES-lib#244] opened 2020-12-15 03:15 UTC
No datagrams appear when using ~~datagram-dump~~ datagram-list for 7125 + Hydrins files

Ex:

/data/ftp/hydrographe/MISSIONS/M20201113/LogData/20201113_192234_FJSaucier_7125_Hydrins.s7k

**Comment by JordanMcManus** [comment] 2020-12-16 15:17
On my side, I see the datagrams when I use datagram-dump.
Try a "make datagram-dump" to rebuild your executable (there was a recent bug with the compare string case insensitive that was making it build the wrong parser).

**Comment by glabmoris** [comment] 2020-12-16 21:11
My mistake, they don't appear when using **datagram-list**

**Comment by JordanMcManus** [comment] 2020-12-17 18:52
This is fixed in #245

**Comment by glabmoris** [comment] 2020-12-17 19:08
Verify that this is the same issue for these files and that it solved the problem:

/data/ftp/hydrographe/MISSIONS/M170515/MBES-seabat/20170518_163937.s7k

This one hangs:
/data/ftp/hydrographe/MISSIONS/M190715/data_16072019/Snippets20190716/2019.07.16_1734 - Noname - 0001.xtf

**Comment by JordanMcManus** [comment] 2020-12-18 15:49
For:
/data/ftp/hydrographe/MISSIONS/M190715/data_16072019/Snippets20190716/2019.07.16_1734 - Noname - 0001.xtf

The problem is not datagram-list. The problem is the data and the XtfParser. It gets stuck in an infinite loop because it reads a packet with 0 section bytes.
```
while(packetIndex < nbBytes){
...
...
packetIndex += sectionBytes; // <--- stuck here because sectionBytes is 0
}
```

This should be moved to its own issue. Even if the file is corrupted, the XtfParser needs to be able to handle this gracefully.

**Comment by JordanMcManus** [comment] 2020-12-18 17:26
For:
/data/ftp/hydrographe/MISSIONS/M170515/MBES-seabat/20170518_163937.s7k

It works fine on my side.

**Closed** 2021-01-13 17:36 UTC
Labels: bug
